### ISSUE TITLE
Need to add `file_removal` when scaffolding file fields. 

### ISSUE THREAD

**Issue by andrewculver** [bullet-train-co/bullet_train-super_scaffolding#17]
Importing from an old to-do. Can we confirm this is working properly?

**Comment by gazayas** [comment]
@andrewculver  Looking into this one now. The `file_removal` button itself is scaffolded:
![Remove Current Document](https://user-images.githubusercontent.com/10546292/163998287-1df37499-fb4c-4fa5-a3dd-39e9e4c289b5.png)

However, removing the file on the edit view and updating the record doesn't actually delete the file, whereas it does work when creating a Tangible Thing. I'll see if I can make some progress on this one.
